import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Calistoga } from "next/font/google";
import Chatbot from "@/app/components/chatbot/Chatbot";

const calistoga = Calistoga({
  subsets: ["latin"],
  weight: "400", 
  variable: "--font-calistoga",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"], // Regular
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Samir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
