import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Calistoga } from "next/font/google";
import Chatbot from "@/app/components/chatbot/Chatbot";
import ClickRipple from "@/app/components/ui/ClickRipple";
import SmoothScroll from "@/app/components/ui/SmoothScroll";
import Noise from "@/app/components/ui/Noise";

const calistoga = Calistoga({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-calistoga",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"], // Regular
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Samir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <SmoothScroll>
          <Noise />
          <ClickRipple />
          {children}
          <Chatbot />
        </SmoothScroll>
      </body>
    </html>
  );
}
